name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: apps/web
      - run: npm run format:check
        working-directory: apps/web
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: functions
      - run: npm run format:check
        working-directory: functions

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: apps/web
      - run: npm run lint
        working-directory: apps/web
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: functions
      - run: npm run lint
        working-directory: functions

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: apps/web
      - run: npm run build
        working-directory: apps/web
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: functions
      - run: npm run build
        working-directory: functions
      - uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist
          if-no-files-found: error

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: apps/web
      - run: npm run test:unit
        working-directory: apps/web
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: functions
      - run: npm run test:unit
        working-directory: functions

  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: apps/web
      - run: npm run test:e2e:install
        working-directory: apps/web
      - run: npm run test:e2e
        working-directory: apps/web

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: apps/web
      - run: npm audit --audit-level=high
        working-directory: apps/web
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: functions
      - run: npm audit --audit-level=high
        working-directory: functions

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: apps/web
      - run: npm run typos
        working-directory: apps/web
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: functions
      - run: npm run typos
        working-directory: functions

  knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: apps/web
      - run: npm run knip
        working-directory: apps/web
      - uses: ./.github/actions/setup-npm-project
        with:
          working-directory: functions
      - run: npm run knip
        working-directory: functions

  deploy_live:
    needs:
      - audit
      - build
      - e2e_tests
      - unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEAL_TRACKER_46346 }}
          channelId: live
          projectId: meal-tracker-46346
